# Generated by Django 4.2.16 on 2024-10-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventroyItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=0)),
                ('created_at', models.DateField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
