# Generated by Django 4.2.16 on 2024-10-17 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firmadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmAdminMOdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, null=True, unique=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inventroyitemmodel',
            name='firmAdmin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firmadmin.firmadminmodel'),
        ),
    ]
